import { useState } from 'react';
import Head from 'next/head';

export default function Home() {
  const [answer, setAnswer] = useState("");
  const [question, setQuestion] = useState("");

  const prompt = `Explain the word "${question}" and give me some exmaple sentences`;

  const generateAnswer = async (e: any) => {
    if (!question) return;
    e.preventDefault();
    setAnswer(""); // clear previous

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt,
      }),
    });

    if (!response.ok) {
      console.error(response.statusText);
    }

    let result = await response.json();
    if (result.error) {
      console.error(result.error);
    }
    setAnswer(result.choices[0].message.content);
  };

  return (
    <>
      <Head>
        <title>English assistant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex max-w-5xl mx-auto flex-col items-center justify-center py-2 min-h-screen">
        <h1 className="sm:text-6xl text-4xl max-w-[708px] font-bold text-slate-900">English Assistant</h1>
        <p className="text-slate-500 mt-5">ask so far</p>
        <div className="max-w-xl w-full">
          <div className="flex mt-10 items-center space-x-3"></div>
          <div className="flex mt-10 items-center space-x-3"></div>
          <textarea
            className="w-full rounded-md border-gray-300 shadow-sm focus:border-black focus:ring-black my-5"
            rows={5}
            placeholder="e.g. Abandon"
            spellCheck={false}
            value={question}
            onChange={(e) => setQuestion(e.target.value)}          
          ></textarea>
          <div className="flex mt-10 items-center space-x-3"></div>
          <button
            className="bg-black rounded-xl text-white font-medium px-4 py-2 sm:mt-10 mt-8 hover:bg-black/80 w-full"
            onClick={generateAnswer}
          >
            Get Answer
          </button>
        </div>
        <div className="space-y-10 my-10">
          <h2 className="sm:text-4xl text-3xl font-bold text-slate-900 mx-auto">Answer Content</h2>
          {
            answer &&
            <div className="space-y-8 flex flex-col items-center justify-center max-w-xl mx-auto">
              <div className="bg-white rounded-xl shadow-md p-4 hover:bg-gray-100 transition cursor-copy border">{answer}</div>
            </div>
          }
        </div>
      </main>
    </>
  )
}
